config/routes.rb
Rails.application.routes.draw do

   devise_for :users 

   resources :users

  resources :photos do
    collection do
      get :results
      get :search
      get :image_boxes
      get :image_carousel

    end
  member do 
      get :download_photo_pic 
    end
  end
  

  get "photo/:id/mail" => "photos#mail", :as => "mail_photo"
  get "photo/:id/send_to_everyone" => "photos#send_to_everyone", :as => "send_to_everyone_photo"

  root to: "photos#index"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user
	mount_uploader :photo_pic, PhotoPicUploader
	

	def send_new_photo_to_all
	Photo.new_photo_message_to_group(Photo.all, self)


		end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :photos
	accepts_nested_attributes_for :photos 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
  session["user_return_to"] || root_path
end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!
  before_action :mail, :send_to_everyone

  def mail
    UserMailer.new_photo_message_one(@photo, current_user).deliver

  end

  def send_to_everyone
    user = User.all 
    user.each do |user|
    UserMailer.new_photo_message_all(@photo, user).deliver
    end
  end


  def index 
    if params[:tag]
      @photos = Photo.tagged_with(params[:tag])
    else
      @photos = Photo.all
    end
  end

  def new
    @new_photo = Photo.new
  end

  def create
    @new_photo = Photo.new(photo_params)
    if @new_photo.save
      redirect_to photos_path
    else
      redirect_to new_photo_path
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      redirect_to photos_path
    else
      redirect_to photo_path
    end
  end

  # def destroy
  #   @photo = Photo.find(params[:id])
  #     if @photo.delete
  #     redirect_to photos_path
  #   end
  # end

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_path }
      format.js
      @photos = Photo.all
    end
  else 
    respond_to do |format|
      format.html { redirect_to photos_path, notice: "update failed." }
      format.js
    end
  end
end

  def search
    @search_results  = Photo.search(params[:search])
    render results_photos_path
  end


  def results
  end 

  def download_photo_pic
    @photo = Photo.find(params[:id])
    file = @photo.photo_pic
    send_file file.path
  end



  def image_boxes
    @photos = Photo.all
  end

  def image_carousel
    @photos = Photo.all
  end


  private

  def photo_params
    params.require(:photo).permit!
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all

    respond_to do |format|
      format.html
      format.xml  { render :xml => @users }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @user }
    end
  end


  def edit
    @user = User.find(params[:id])
  end


  class UsersController < ApplicationController

  def create
    @user = User.new(params[:user])
 
    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver
 
        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

  
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper

	def tags(tag_list)
  markup = ""
  tag_list.each do |tag|
    markup += content_tag(:span, tag, :class => "tag")
  end
  raw(markup)
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pik Yo Mood!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://code.jquery.com/jquery-1.10.2.js"></script>

</head>
<body>
	 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


   <style>

/*  p {
    margin: 0;
    color: blue;
  }
  div,p {
    margin-left: 10px;
  }
  span {
    color: blue;
  }

  .pointer {
    font-size: 150%;
    cursor: pointer;
  }

  #containertwo {
    position: absolute;
    margin: 0px;
    padding: 0px;
    width: 100%;
    height: 100%;
    overflow: hidden;  
}

.left-right {
    overflow:hidden;
    height:200px;
    width:200px;
    position:relative;
    background-color:#333;
    clear: left;
}
div.l1,div.l2,div.l3 {
    width:200px;
    height:200px;
    position:absolute;
    top:0;
    right:-200px;
    color:#fff;
}
a.l1,a.l2,a.l3 {
    display: block;
    width: 50px;
    height: 50px;
    float: left;
    cursor: pointer;
    opacity: 0.6;
}
a:hover {
    opacity: 1
}

.l1{
    color: red;
    background-color:red;
}
.l2{
    color: green;
    background-color:green;
}
.l3{
    color: blue;
    background-color:blue;
}



ul.featureBoxes  {
  color:#eb8f0d;
  float:left;
  list-style:none;
  width:293px;
}

.paddingRight {
  padding-right:200px;
}

ul.featureBoxes li {
  padding: 0 0 0 10px;
}

ul.featureBoxes li p {
  color:#5f717a;
  line-height:120px;
  margin-left:100px ;
}


.imagesboxes {
  background-color:#8a9e3b;
  color:#fff;
  cursor:pointer;
  display:block;
  font-size:20px;
  height:30px;
  line-height:30px;
  list-style:none;
  margin:20px 0 10px 0;
}

.imagesboxes:hover {
  background-color:#336333;
}

.imagesboxeslistings {
  list-style-position:outside;
  list-style-type:square;
  padding-left:20px;
}

ul.imagesboxeslistings li p {
  margin:0;
  padding:0;
}

 .awesome {
    background: #de9a44;
    margin: 3px;
    width: auto;
    height: auto;
    display: none;
    float: left;
  }

.fadein {
    position:relative;
    height:320px;
    width:320px;
}

.fadein img {
    position:absolute;
    left:0;
    top:0;
}

#divone, #divtwo, #divthree, #divfour,#divfive, #divsix  {
position:absolute;
display: none;
}
/*
#pics {
width:100px;
height:100px;
}*/

#pics img {
margin-left:125px;
width:400px;
height:300px;
}
*/

  </style>

   
  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="/photos" class="navbar-brand">Pik Yo Mood!</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
          	

            <li class="">
              
            <% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to 'Mail a Dot', image_boxes_photos_path %></li>
  <li><%= link_to 'Sorta Carousel', image_carousel_photos_path %></li>
<% else %>
<li><%= link_to 'Login', new_user_session_path %></li>
<li><%= link_to 'Sign up', new_user_registration_path %></li>

<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Create New', new_photo_path %></li>
<% end %>
            </li>
            
          
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
  <li><a href="/events">Hi! <%= current_user.email %></a></li>
  <% end %>
          </ul>

        </div>
      </div>
    </div>


    <div class="container">

      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-6">
            <%= yield %>
          </div>

      
 <script type="text/javascript">

$(document).ready(function() { 
    $('#divone').fadeIn(1500).delay(3500).fadeOut(1500);
    $('#divtwo').fadeIn(1500).delay(3500).fadeOut(1500);
    $('#divthree').fadeIn(5000).delay(3500).fadeOut(5000);
    $('#divfour').fadeIn(1500).delay(3500).fadeOut(1500);
    $('#divfive').fadeIn(1500).delay(3500).fadeOut(1500);
    $('#divsix').fadeIn(5000).delay(3500).fadeOut(5000);
    $('#divseven').delay(5000).fadeIn(1500);
});
</script>
 
 
<script>

$('#form').submit(function() {
if ($.trim($("#photo_name").val()) === "" ){
alert('Please fill out the Title of the Movie');
return false;
}
});
</script>


    <script>

$(function(){
  $("ul.imagesboxeslistings").hide();

  $(".imagesboxes").click(function() {
    $(this).next().find('ul.imagesboxeslistings').slideToggle(300);
    return false;
  });
});

</script>

<div class="awesome"></div>
<div class="awesome"></div>  
<div class="awesome"></div>  
<div class="awesome"></div>  
<div class="awesome"></div>      
    
</div>
         

          </div>
        </div>
      </div>



</body>
</html>

app/views/photos/_form.html.haml
.container_form
  .col-lg-8.col-md-8.col-sm-8
    .span1
      .span10
      = f.label :name
      = f.text_field :name, class: "form-control"
      %br
      = f.file_field :photo_pic





 
 

app/views/photos/_form_two.html.haml
/ = @photos

/ %br
/ - @photos.each do |m|
/   .col-sm-3.col-xs-6
/     .panel.panel-default
/       .panel-thumbnail
/       = image_tag m.photo_pic.url ,:style => "max-width: 100%"
/       .panel-body


/ = image_tag @photos.photo_pic.url
      
    

app/views/photos/_photos.html.haml
.row-4
  - @photos.each do |photo|
    .col-sm-3.col-xs-6
      .panel.panel-default
        .panel-thumbnail
        = image_tag photo.photo_pic.url ,:style => "max-width: 100%"
        .panel-body
          %p.lead
            = photo.name  
            %p
            %a{:href => "/photos/#{photo.id}/edit"} Edit
            = link_to "Not my Mood, Yo!", photo, :remote => true, :confirm => 'Are you sure?', :method => :delete
            %br

app/views/photos/_search.html.haml
.top-search 
  %br
  = form_tag search_photos_path, method: "get" do
    = text_field_tag 'search[name]'
    = submit_tag "SEARCH"

app/views/photos/destroy.js.erb
$("#photos_list").html("<%= escape_javascript( render(:partial => "photos") ) %>");

app/views/photos/edit.html.haml
= form_for @photo, url: "/photos/#{@photo.id}" do |f|
	= render "form", f: f
	= f.submit "EDIT"



= link_to "DELETE",  {:action => "destroy", :id => "#{@photo.id}"}, :method => :delete, :class => "icon-delete", :confirm => "Are you sure"

app/views/photos/image_boxes.html.haml
%h2 Do You Mail a'dot
%h3 click a dot and mail away!
%br
- @photos.each do |m|
  %ul.featureBoxes.paddingRight
  %li.imagesboxes.features 
    %li
      %ul.imagesboxeslistings
        .col-sm-3.col-xs-6
          .panel.panel-default
            .panel.thumbnail
              = image_tag m.photo_pic.url ,:style => "max-width: 100%"
              .panel-body
                %p.lead
                  = m.name  
                  %p
                  %a{:href => "/photos/#{m.id}/edit"} Edit
                  %a{:href => "/photos/#{m.id}/edit"} Delete
                  %br
                  = button_to "More Info!", photo_path(m), method: :get
                  = link_to 'Email to One!', mail_photo_path(m)
                  %br
                  = link_to 'Send to Everyone!', send_to_everyone_photo_path(m)

app/views/photos/image_carousel.html.haml
.col-sm-8.col-xs-8
  #pics
    .img
    #divone{:height => "100", :width => "100"}
      = image_tag @photos.first.photo_pic.url
    #divtwo{:height => "100", :width => "100"}
      = image_tag @photos.second.photo_pic.url
    #divthree{:height => "100", :width => "100"}
      = image_tag @photos.third.photo_pic.url
    #divfour{:height => "100", :width => "100"}
      = image_tag @photos.fourth.photo_pic.url
    #divfive{:height => "100", :width => "100"}
      = image_tag @photos.fifth.photo_pic.url
    %img#divsix{:height => "100", :width => "100"}
      = image_tag @photos.last.photo_pic.url
    %img#divseven{:height => "100", :width => "100"}
      = image_tag @photos.first.photo_pic.url
    / %img#diveight{:height => "100", :width => "100"}
    /   = image_tag @photos.eighth.photo_pic.url
    / %img#divnine{:height => "100", :width => "100"}
    /   = image_tag @photos.ninth.photo_pic.url

app/views/photos/index.html.haml
#photos_list= render :partial => "photos"
           

/ = link_to "Edit", edit_photo_path(photo), :remote => true
/ = link_to "Destroy", photo, :remote => true, :confirm => 'Are you sure?', :method => :delete








          

app/views/photos/new.html.haml
%h2 Create New and it Emails to You!
%br
.form#form
  = form_for @new_photo, url: photos_path do |f|
    = render "form", f: f
    = f.submit "Create New"

app/views/photos/results.html.haml
- @search_results.each do |d|
  .col-sm-4.col-xs-6
    .panel.panel-default
      .panel-thumbnail

        = image_tag d.photo_pic.url ,:style => "max-width: 100%"

      .panel-body
        %p.lead 
        = d.title
        %p 
          = d.description
          %br
        %p
          %a{:href=>"/photos/#{d.id}/edit"} EDIT
          %a{:href=>"/photos/#{d.id}/edit"} DELETE
          %br
          = link_to "Download Photo", download_photo_pic_photo_path(d)

app/views/photos/show.html.haml
- @photo.each do |m|
  .col-sm-3.col-xs-6
    .panel.panel-default
      .panel-thumbnail
        = image_tag m.photo_pic.url ,:style => "max-width: 100%"


= link_to 'Email these photos', mail_photo_path(@photo)
        

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>